### PR TITLE
Reject promise instead of throwing if coroutine throws before 1st yield 

### LINKED ISSUE #97: Coroutines : Exceptions thrown before the 1st yield are rethrown instead of rejecting the promise
If a coroutine throws **after** its 1st yield, then the promise is rejected, as expected :
```php
$result = Promise\coroutine(function () {
    yield true;
    thrown new \Exception();
})->then(null, function () { return false; })->wait();

// OK, $result === false
```

But if it throws before the 1st yield, the exception is not caught :
```php
$result = Promise\coroutine(function () {
    thrown new \Exception();
    yield true;
})->then(null, function () { return false; })->wait();

// KO, Uncaught Exception
```

### PR DESCRIPTION
**Pull request by yched**
Fixes #97

### CODE REVIEW

File: src/Coroutine.php [hunk 1]
```diff
@@ -65,7 +65,15 @@ public function __construct(callable $generatorFn)
                 $this->currentPromise->wait();
             }
         });
-        $this->nextCoroutine($this->generator->current());
+        try {
+            $this->nextCoroutine($this->generator->current());
+        }
+        catch (\Exception $exception) {
```
Comment (Tobion) [inline src/Coroutine.php]: this should be on the same line as the closing bracket. see coding style below in `_handleFailure`

Comment (yched) [reply src/Coroutine.php]: Sure, done

**Comment by Tobion** [comment]
Thank you @yched
