### PR TITLE
Use incrementing counter to generate pending indexes.

### LINKED ISSUE #133: each_limit skipping promises and failing with "Invoking the wait callback did not resolve the promise"
**PHP version**: 7.4.9

**Description**
I have some code that downloads and processes sequences of pages multiple times.  Multiple instances of these downloads are gathered up and passed to each_limit to process the chains at a limited concurrency.

With 1.3.1 this process works overall.  After upgrading to 1.4.0 the script fails with 

	Fatal error: Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise

The script also appears to skip some of the promises.

**How to reproduce**
I've reproduced the issue with the following example code:

	<?php
	require 'vendor/autoload.php';

	use GuzzleHttp\Promise\Promise;
	use function GuzzleHttp\Promise\each_limit;

	class Downloader {
	    public function download($upper){
		return $this->step1($upper)
		    ->then(function($result){
			return $this->step2($result);
		    })->then(function($result){
			return $this->step3($result);
		    })->then(function($result){
			return $this->step4($result);
		    });
	    }

	    private function step1($upper){
		$upper = $upper & 0xFF00;

		return $promise = new Promise(function() use (&$promise, $upper){
		    $promise->resolve($upper);
		});
	    }

	    private function step2($result){
		$result = $result | 0x02;

		return $promise = new Promise(function() use (&$promise, $result){
		    $promise->resolve($result);
		});
	    }

	    private function step3($result){
		$result = $result | 0x04;

		return $promise = new Promise(function() use (&$promise, $result){
		    $promise->resolve($result);
		});
	    }

	    private function step4($result){
		return $result | 0x08;
	    }
	}

	function generateDownloadPromises(Downloader $dl, $entries){
	    foreach ($entries as $item){
		yield $dl->download($item << 8)->then(function($result){
		    echo 'Received value: ' . $result . PHP_EOL;

		    return $result;
		});
	    }
	}

	$dl = new Downloader();
	$generator = generateDownloadPromises($dl, range(1, 10));
	each_limit($generator, 3, function($result, $key){
	    echo '[' . $key . '] Promise resolved successfully to ' . $result, PHP_EOL;
	}, function($reason, $key){
	    echo '[' . $key . '] Failed to resolve promise', PHP_EOL;
	    var_dump($reason);
	})->wait();

**Results**
Running the above on 1.3.1 yields the output:

	Received value: 270
	[0] Promise resolved successfully to 270
	Received value: 526
	[1] Promise resolved successfully to 526
	Received value: 782
	[2] Promise resolved successfully to 782
	Received value: 1038
	[3] Promise resolved successfully to 1038
	Received value: 1294
	[4] Promise resolved successfully to 1294
	Received value: 1550
	[5] Promise resolved successfully to 1550
	Received value: 1806
	[6] Promise resolved successfully to 1806
	Received value: 2062
	[7] Promise resolved successfully to 2062
	Received value: 2318
	[8] Promise resolved successfully to 2318
	Received value: 2574
	[9] Promise resolved successfully to 2574

While on 1.4.0 it yields:

	Received value: 270
	[0] Promise resolved successfully to 270
	Received value: 1038
	[3] Promise resolved successfully to 1038
	Received value: 1294
	[4] Promise resolved successfully to 1294
	Received value: 1550
	[5] Promise resolved successfully to 1550
	Received value: 1806
	[6] Promise resolved successfully to 1806
	Received value: 2062
	[7] Promise resolved successfully to 2062
	Received value: 2318
	[8] Promise resolved successfully to 2318
	Received value: 2574
	[9] Promise resolved successfully to 2574
	PHP Fatal error:  Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise in G:\xxx\vendor\guzzlehttp\promises\src\Create.php:62
	Stack trace:
	#0 G:\xxx\vendor\guzzlehttp\promises\src\Promise.php(72): GuzzleHttp\Promise\Create::exceptionFor('Invoking the wa...')
	#1 G:\xxx\each_bug.php(66): GuzzleHttp\Promise\Promise->wait()
	#2 {main}
	  thrown in G:\xxx\vendor\guzzlehttp\promises\src\Create.php on line 62

**Additional context**

Aside from the unexpected exception in 1.4.0, you can see that the indexes [1] and [2] are missing, those promises are skipped and never processed.

Looking through and testing various previous commits it appears this issue was introduced by commit 27c7a89.  The code works when using the prior commit 956c5d1

### PR DESCRIPTION
**Pull request by kicken**
Using end() moves the internal array pointer and breaks the
iteration taking place in the promises wait function.

Use an incrementing counter to generate unique indexes for
the pending array instead.

Fixes #133

### CODE REVIEW

File: src/EachPromise.php [hunk 1]
```diff
@@ -10,6 +10,8 @@ class EachPromise implements PromisorInterface
 {
     private $pending = [];
 
+    private $nextPendingIndex = 0;
```
Comment (Tobion) [inline src/EachPromise.php:13]: seems fine to do it this way. But I suggest to reset the counter in the clear function in https://github.com/guzzle/promises/blob/0e3f22db085e896f13c0a4e6cf3d916f65de2358/src/EachPromise.php#L123

**Review by Tobion — CHANGES_REQUESTED** [review]

**Review by GrahamCampbell — APPROVED** [review]

**Review by Tobion — APPROVED** [review]

**Comment by Tobion** [comment]
Thank you @kicken
